# Generated by Django 4.1.2 on 2022-12-30 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_user_number_followers_user_number_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followerss',
            field=models.ManyToManyField(null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
