# Generated by Django 4.1.2 on 2022-12-30 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_user_followerss_remove_user_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followerss',
            field=models.ManyToManyField(null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(null=True, related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='number_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='number_following',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
