# Generated by Django 4.1.2 on 2023-01-03 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_remove_post_likers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
